Front/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/urls.py
from django.urls import path
from .views import *
urlpatterns=[
    path('add_emp/', add_emp),
    path('send/', send_message)
    ]

myapp/models.py
from pydoc import describe
from django.db import models



class Emp(models.Model):

    name = models.TextField(max_length=255,verbose_name="name", )
    age = models.IntegerField(verbose_name="age")

myapp/forms.py
from django import forms

from . import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


class EmpForm(forms.Form):
    alphanumeric = RegexValidator(r'^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
    name = forms.CharField(min_length=5, label="name", error_messages={"required": "This field cannot be empty!",
                                                                    "min_length": "The user name is too short。"},validators=[alphanumeric])
    age = forms.IntegerField(label="age")
    r_salary = forms.DecimalField(max_digits=8,  label="Please enter your password again")
    email =forms.EmailField()
    number=forms.IntegerField(label="number")
    country=forms.CharField(max_length=20,label="country")


    def clean_name(self):
        val = self.cleaned_data.get("name")


        if val.isdigit():
            raise ValidationError("The user name cannot be a pure number")
        elif models.Emp.objects.filter(name=val):
            raise ValidationError("User name already exists!")
        else:
            return val

    def clean(self):
        val = self.cleaned_data.get("salary")
        r_val = self.cleaned_data.get("r_salary")


        if val == r_val:
            return self.cleaned_data
        else:
            raise ValidationError("Please confirm whether the wages are consistent.")

myapp/views.py
from django.shortcuts import render, redirect
from .forms import EmpForm
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from .import models

def add_emp(request):
    if request.method == "GET":
        form = EmpForm()
        return render(request, "polls/from.html", {"form":form})
    else:
        form = EmpForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            data.pop("r_salary")
            models.Emp.objects.create(**data)
            return redirect('/admin')
        else:
            clear_errors = form.errors.get("all")
            return render(request, "polls/from.html", {"form": form, "clear_errors": clear_errors})


def send_message(request):
    email=EmailMessage(
              "Web programming:back end",
              "My content",
              "26072019oppo@gmail.com",
              ['26072019oppo@gmail.com','200103520@stu.sdu.edu.kz'],
              headers={'Message-ID':'foo'},
        )

    email.send(fail_silently=False)
    return render(request,'polls//success.html')

myapp/templates/polls/from.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<h3>Registered account</h3>
<form action="" method="post" novalidate>
    {% csrf_token %}
    <div>
        <label for="id_{{ form.name.name }}">name</label>
        {{ form.name }} <span>{{ form.name.errors.0 }}</span>
    </div>
    <div>
        <label for="id_{{ form.age.name }}">age</label>
        {{ form.age }} <span>{{ form.age.errors.0 }}</span>
    </div>

    <div>
        <label for="id_r_salary">password</label>
        {{ form.r_salary }} <span>{{ form.r_salary.errors.0 }}{{ clear_errors.0 }}</span>
    </div>
    <div>
        <label for="email">email</label>
        {{ form.email}} <span>{{form.email.errors.0}}</span>
    </div>
    <div>
        <lebel for="number">phone number</lebel>
        {{form.number}}<span>{{form.number.errors.0}}</span>
    </div>
    <div>
        <lebel for="country">country</lebel>
        {{form.country}}<span>{{form.country.errors.0}}</span>
    </div>
    <input type="submit">
</form>
</body>
</html>

myapp/templates/polls/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 Sent ssuccessfully!
</body>
</html>